### ISSUE TITLE
wired login/signup error

### ISSUE THREAD

**Issue by ericxsun** [wandb/local#64]
Pre:
- Docker version 20.10.12, build e91ed57
- wandb, version 0.12.14
- wandb local image latest

With the following actions:

```
# start a new docker volume

docker stop wandb-local
docker volume rm wandb

docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

0) then, trigger the `localhost:8080/logout`

<img width="529" alt="image" src="https://user-images.githubusercontent.com/1772912/164471236-e760ead4-ffd3-423d-a8bb-aeb604338e06.png">

and then I can see the` login ` and  `add license` :

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1772912/164471466-d5c4f320-8e73-4306-a121-7ce230a915c5.png">

1) goto: `Add license`   -> finally get `http://localhost:8080/system-admin/`

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1772912/164475152-f0ebb4fe-6a28-4ac7-bfe3-ff4ffa86ff9f.png">

the `Login` links to `http://localhost:8080/system-admin/login`, a invalid link address (`403 Forbidden`)

2) goto: `Login` in `0)` -> finally get `http://localhost:8080/signup`
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/1772912/164475761-6984ea4e-66a1-4a5d-9154-66930be6d1f3.png">

click `continue`, I get the error:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1772912/164475851-bec9fd83-d76a-45c8-a050-f051f6ed1fcc.png">

3) set user and password through wandb bash cmd
```
docker exec -it wandb-local bash

wandb@66de73cf1e02:~$ cat /vol/env/users.htpasswd

only one line: local@wandb.com:.....

## create a user:
wandb@66de73cf1e02:~$ /usr/local/bin/local password test@gmail.com
Enter password for test@gmail.com:
xxxxx
User updated
```

and then goto `http://localhost:8080/logout`, and `Login`, it automatically jumps to the signup screen, and I get the same as described in `2)` above.

4) try to restart after creation of the test@gmail.com in `3)` and try again
```
docker stop wandb-local
docker run --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```
and then goto `http://localhost:8080/logout`, and `Login`, it automatically jumps to the signup screen, and I get the same as described in `2)` above.

5) goto wandb shell and set something:
```
# rm local@wandb.com:.....   in /vol/env/users.htpasswd, then only one line left:
test@gmail.com:....

# restart mysql and outside the wandb docker, restart docker wandb local and re-login wandb shell, dive into mysql:
mysql -u wandb_local -p

select * from wandb_local.users;

the username of test@gmail.com is empty, then update it:
update wandb_local.users set username='test' where email = 'test@gmail';

# restart mysql and outside the wandb docker, restart docker wandb local
/etc/initd/mysql restart

docker run -e LOCAL_RESTORE=true --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

re-goto `http://localhost:8080/logout`, and login, failed into signup page(it is different from the page in `2)`

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1772912/164483769-2a56572c-f9b9-42a8-9e7c-6ad9d44c452b.png">

and re signup a new user `test2`,  a wired error ocurred
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/1772912/164484210-2bd9a9cc-ea1b-4d28-9030-052daf8bf015.png">

-----
It's really boring, for so many tries, I still cannot login successfully.

**Comment by ericxsun** [comment]
One more try:

step 1: create and start a new volume
```
docker stop wandb-local
docker volume rm wandb

docker run -e LOCAL_RESTORE=true --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

**Do not open the localhost:8080 pages.**

step 2: login wandb docker shell and remove line `local@wandb.com...` in `/vol/env/users.htpasswd`
```
docker exec -it wandb-local bash

vi /vol/env/users.htpasswd  # remove line: local@wandb.com... 
cat /vol/env/users.htpasswd
```
![image](https://user-images.githubusercontent.com/1772912/164608603-3a3d4192-d35f-4f14-9eb4-dfce286707c6.png)

*NB*: I guess the param `-e LOCAL_RESTORE=true` led to the line `restore@wandb.com:....`

step 3: create new user `test@gmail.com`
```
/usr/local/bin/local password test@gmail.com

cat /vol/env/users.htpasswd 
```
![image](https://user-images.githubusercontent.com/1772912/164608994-2226212e-b0f7-4799-9fac-4cb4f7bc7b49.png)

and login mysql through `mysql -u wandb_local -p` to see some infos:
![image](https://user-images.githubusercontent.com/1772912/164609199-3e569a84-71ef-4f86-ae58-07bc035af4bd.png)

step 4: restart mysql and docker wandb, 
```
# in wandb docker shell
/etc/init.d/mysql restart

# in host
docker stop wandb-local
docker run -e LOCAL_RESTORE=true --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

and trigger the login or signup page `http://localhost:8080/logout` and click `Login`, input the created user in `step 3`, and it will bring me to the signup page, now **DO NOT DO ANY THING ON THE PAGE**

step 5: login wandb docker shell

step 5.1: see things change in mysql:  `mysql -u wandb_local -p`
![image](https://user-images.githubusercontent.com/1772912/164609900-d7146fd2-f685-4d6c-ac9f-fe37129d98fd.png)

step 5.2: update things in mysql: 
1) change `NULL` to `test` for `email=test@gmail.com`: `update wandb_local.users set username = 'test' where email = 'test@gmail.com';`
2) add one entity in `entities` for user `test@gmail.com`: `insert into wandb_local.entities(created_at, name) values('2022-04-22 02:03:16', 'test');`

![image](https://user-images.githubusercontent.com/1772912/164610446-b534a1ba-187a-404e-b178-a587feee626b.png)

**Comment by vanpelt** [comment]
Hey @ericxsun we're working on a fix for this in the next release.  You should never under any circumstances manually alter database records or create entities, that will potentially get you into an even more funky state but I'm glad you got in and apologies for this bug.

**Comment by better629** [comment]
@ericxsun follow your steps, but still can't login in.sign up with pre-create account, but still occurs with `entity already exists for the user xxxx`. But can login in with restore account.

**Comment by ericxsun** [comment]
> 

@better629  with the latest try(https://github.com/wandb/local/issues/64#issuecomment-1106030481), I do not meet such same error(`entity already exists for the user xxxx`). Does the username (`xxxx`) of signup page is same as the pre-create account `xxxx@email-address`. If same, I think you can show the infos in `wandb_local.entities`, and remove and retry. Otherwise, try with the same name. Hope you could login.

**Comment by better629** [comment]
@ericxsun I use the email with other username which I update the sql table. If it should be the same, I will try it.
After login in, do u meet the backend api problem when save the license?

**Comment by ericxsun** [comment]
> @ericxsun I use the email with other username which I update the sql table. If it should be the same, I will try it. After login in, do u meet the backend api problem when save the license?

No, I didn't meet the error. All is okay:

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/1772912/165010456-82c87560-4c82-42fb-af41-8e03048ec80f.png">

**Comment by Jeffrey28** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/26816785/168460987-9c624cc4-1d9f-42d1-bdd9-85010d82a756.png">
There has been no change in this interface. Is there any method to tackle it?

**Comment by ericxsun** [comment]
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/26816785/168460987-9c624cc4-1d9f-42d1-bdd9-85010d82a756.png">
> 
> There has been no change in this interface. Is there any method to tackle it?

It'll cost much time to init the environment

Waiting!!!

or try again(if it cost too much time) :

```
docker stop wandb-local
docker volume rm wandb

docker run -e LOCAL_RESTORE=true --rm -d -v wandb:/vol -p 8080:8080 --name wandb-local wandb/local
```

Wish you good luck

**Comment by Jeffrey28** [comment]
I have tried and waited for a long time almost one day. It still doesn't work.

**Comment by vanpelt** [comment]
@Jeffrey28 can you share the output of `docker logs wandb-local`

**Comment by Jeffrey28** [comment]
> 
Here it comes!
```
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
```

**Comment by Jeffrey28** [comment]
And there is no a file named logs in the folder /var.

**Comment by Jeffrey28** [comment]
```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling restore mode

Login at http://localhost:8080/api/login
  username: restore@wandb.com
  password: fJqL0uj1fewDqg==

*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
*** Loading settings...
2022/05/18 02:59:40 Created default user
2022/05/18 02:59:40 Generating new session key for auth...
2022/05/18 02:59:40 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 49
*** Setting up mysql database...
*** Starting wandb servers...
*** Minio still starting up...
*** Configuring minio...
Bucket created successfully `local/local-files`.
*** Minio still starting up...
Successfully added arn:minio:sqs:wandb-local:_:redis
*** Migrating database...
[mysql] 2022/05/18 03:04:00 packets.go:37: read tcp 127.0.0.1:60638->127.0.0.1:3306: i/o timeout
[mysql] 2022/05/18 03:04:00 connection.go:299: invalid connection
panic: 2 errors occurred:
	* migration failed in line 0: ALTER TABLE runs ADD COLUMN deleted_at datetime DEFAULT NULL;
 (details: invalid connection)
	* driver: bad connection in line 0: SELECT RELEASE_LOCK(?)



goroutine 1 [running]:
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/migrate/main.go:125 +0x8d6
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
```

**Comment by vanpelt** [comment]
The database is timing out when migrating.  There's an issue with your docker filesystem driver.  Can you provide answers to:

1. Why are you running a local server?
2. What OS and docker version are you using?

**Comment by Jeffrey28** [comment]
> 

1. Running a local server is useful when the network is poor. I often encounter data cannot be uploaded and network errors. 
2. Ubuntu 20.04, Docker version 20.10.16

**Comment by vanpelt** [comment]
Hmm, let's try the following and see if things come up:

> docker stop wandb-local
> docker rm volume wandb
> docker run -d --rm -v wandb:/vol/env:delegated -p 8080:8080 --name wandb-local wandb/local:latest
> docker logs -f wandb-local

Hopefully we don't see any errors in those logs and everything comes up after ~5 minutes or so.  The main change here is adding the `:delegated` flag to the volume mount.  That should improve disk performance.

**Comment by Jeffrey28** [comment]
> Hmm, let's try the following and see if things come up:
> 
> > docker stop wandb-local
> > docker rm volume wandb
> > docker run -d --rm -v wandb:/vol/env:delegated -p 8080:8080 --name wandb-local wandb/local:latest
> > docker logs -f wandb-local
> 
> Hopefully we don't see any errors in those logs and everything comes up after ~5 minutes or so. The main change here is adding the `:delegated` flag to the volume mount. That should improve disk performance.

Still same errors.
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
*** Loading settings...
2022/05/19 00:19:09 Created default user
2022/05/19 00:19:09 Generating new session key for auth...
2022/05/19 00:19:09 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 987
*** Setting up mysql database...
*** Starting wandb servers...
*** Configuring minio...
Bucket created successfully `local/local-files`.
Successfully added arn:minio:sqs:wandb-local:_:redis
*** Migrating database...
[mysql] 2022/05/19 00:23:30 packets.go:37: read tcp 127.0.0.1:60560->127.0.0.1:3306: i/o timeout
[mysql] 2022/05/19 00:23:30 connection.go:299: invalid connection
panic: 2 errors occurred:
	* migration failed in line 0: ALTER TABLE runs ADD COLUMN deleted_at datetime DEFAULT NULL;
 (details: invalid connection)
	* driver: bad connection in line 0: SELECT RELEASE_LOCK(?)



goroutine 1 [running]:
main.main()
	/mnt/ramdisk/core/services/gorilla/cmd/migrate/main.go:125 +0x8d6
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
*** Starting wandb servers...
*** All services started
*** Access W&B at http://localhost:8080
!!! Unable to start backend, see logs at /var/logs.  Trying again in 1 minute
!!! Set the environment variable LOCAL_RESTORE=true if you're unable to login to the admin console

**Comment by vanpelt** [comment]
Can you share the mysql logs?

docker exec -it wandb-local bash
cat /var/log/mysql.log

**Comment by Jeffrey28** [comment]
```
wandb@e37bc2627b9b:~$ cat /var/logs/mysql.log
cat: /var/logs/mysql.log: No such file or directory
wandb@e37bc2627b9b:~$
```

**Comment by nate-wandb** [comment]
Hi @ericxsun are there any log files within `/var/logs/` and if so could you send the contents of those?

**Comment by nate-wandb** [comment]
@ericxsun I wanted to follow up on this and see if you still needed help with this?

**Comment by ericxsun** [comment]
> @ericxsun I wanted to follow up on this and see if you still needed help with this?

No, I've fixed it. You can refer to https://github.com/wandb/local/issues/64#issuecomment-1106030481.

**Comment by Guitaricet** [comment]
I think wandb is amazing and I would really love to be able to use it locally, but this bug exists for at least 3 months now and haven't been resolved. I wasn't able to successfully run wandb inside a kubernetes environment after hours of looking at the logs and the github issues. I might be wrong, but at least to me this bug seems critical.

**Comment by Guitaricet** [comment]
**UPD:** it looks like this problem resolves if you use port 8080 to launch wandb server **and to connect to it**. E.g., `port-forward 8080:8080`. At least the docker version of wandb works for me (`wandb version 0.12.21`).

**Comment by azarezade** [comment]
I still have the same error. After login for first time and signup using wandb UI, I can login and see my profile, but if I logout and then I can't login anymore and receive `401 Unauthorized` error `"error": "user not found"`.
Here is my docker-compose.yml:

```docker-compose
version: '3'
services:
  wandb-local:
    image: wandb/local
    container_name: wandb-local
    ports:
      - "8080:8080"
    volumes:
      - data:/vol
    environment:
      - HOST=http://<my-host>:8080
    restart: unless-stopped
volumes:
  data:
```
